### ISSUE TITLE
unable to run unit tests

### ISSUE THREAD

**Issue by jonericcook** [tokenika/eosfactory#176]
@stefanzarembinski 

eosfactory - v3.3.0
nodeos v1.8.1

```
Work-MacBook-Pro:eosfactory joneric.cook$ python3 tests/hello_world.py

###  SCENARIO:
Create a contract from template, then build and deploy it.

Removing testnet cache for prefix `_127_0_0_1_8888_`
E
======================================================================
ERROR: setUpClass (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/hello_world.py", line 38, in setUpClass
    reset()
  File "/Users/joneric.cook/eosfactory/eosfactory/core/manager.py", line 192, in reset
    clear_testnet_cache()
  File "/Users/joneric.cook/eosfactory/eosfactory/core/manager.py", line 36, in clear_testnet_cache
    teos.kill_keosd() # otherwise the manager may protects the wallet files
  File "/Users/joneric.cook/eosfactory/eosfactory/core/teos.py", line 871, in kill_keosd
    kill(os.path.splitext(os.path.basename(config.keosd_exe()))[0])
  File "/Users/joneric.cook/eosfactory/eosfactory/core/teos.py", line 848, in kill
    pids = get_pid(name)
  File "/Users/joneric.cook/eosfactory/eosfactory/core/teos.py", line 544, in get_pid
    processes = [p.info for p in psutil.process_iter(attrs=["pid", "name"]) \
  File "/Users/joneric.cook/eosfactory/eosfactory/core/teos.py", line 545, in <listcomp>
    if name in p.info["name"]]
TypeError: argument of type 'NoneType' is not iterable

----------------------------------------------------------------------
Ran 0 tests in 0.053s

FAILED (errors=1)
```

**Comment by stefanzarembinski** [comment]
Thank you for the message.
The issue is solved with a pull request by @kdmukai.

**Comment by jonericcook** [comment]
I checked the pull requests and did not see a PR that is recent. I am still getting those errors and am up to date with the eosfactory repo. Would you be able to offer any help on how to resolve the issues im facing?
